### ISSUE TITLE
Adapt to tensorforce#memory

### ISSUE THREAD

**Issue by lefnire** [lefnire/tforce_btc_trader#6]
TensorForce's [memory](https://github.com/reinforceio/tensorforce/tree/memory) branch [supposedly fixes](https://gitter.im/reinforceio/TensorForce?at=5a61bf23e014122650646586) a major flaw in the PPO implementation. It's a pretty wild-west branch for now, and I've started [my own branch](https://github.com/lefnire/tforce_btc_trader/tree/memory) to follow it. I'm gonna put that on hold until they merge their branch into master and cut a release. We'll need to adapt to the new hyperparameters introduced (adding them to our hypersearch framework).

**Comment by lefnire** [comment]
BTW @TalhaAsmal I'm doing my recent work on the #memory branch, which tracks TensorForce's #memory branch. In case you're diving in deep, might benefit from their recent updates

**Comment by lefnire** [comment]
@TalhaAsmal I did a heavy-handed force-push to #memory. I was in flux using that as a personal dev branch (I'm now using #tmp as my dirty branch). I won't be force-pushing to #memory anymore, so you can work from it safely - sorry for that. 

You'll want to rebase your work to it (easiest is probably: (1) create a new branch from #memory, (2) cherry-pick your own branch's commits one-by-one). After following some conversation on TensorForce's Gitter channel, looks like 0.3.5.1 is pretty much non-functional (you won't get any models to converge); that the commits in tensorforce#memory fix _many_ problems. That's to say, our tforce_btc_trader#master is non-functional.

A big noteable recent change. tensorforce#memory switches Policy Gradient models' batching from timestep-batching to episode-batching. Timestep-batching gave us control over explicit batch sizes (1024 means 1024 timesteps, aka 1024 rows/datapoints to send to TensorFlow). Episodes on the other hand are however many timesteps the agent stays alive (doesn't dip below 0 value/cash, doesn't HODL too long). Could be 10k timesteps; could be 100k. Turned out this buffer would fill up pretty fast and crash my GPU (1080 ti, aint nothing to shake a stick at). In order to make episode-batching work, I had to reduce a _lot_ of dimensional parameters. Reduced `batch_size`, max steps per episode (from 20k to 6k; also corresponding `punish_repeats`), and importantly the dimensionality of each timestep's state (aka the features). I added an AutoEncoder to reduce a timestep's dimensions from ~22 (plus/minus a bunch depending on arbitrage & indicators) to 6. Pretty damn destructive. I've got some ideas to improve this situation going forward: 

a. Improve the autoencoder's performance. Currently has a ~2% MSE, if we can widdle then maybe it's find to do what we're doing.
b. Switch from PPO to DDPG, which I believe uses timestep-batching instead of episode. It's a new model in tensorforce#memory, and actually [one I've seen](https://arxiv.org/pdf/1706.10059.pdf) used for trading. An important bit is to stick with continuous actions, so it can buy/sell whatever amount. eg, DQNs require discrete actions.

**Comment by TalhaAsmal** [comment]
I've been testing out the memory branch of this and tensorforce since last night, so not much to stay yet.

I've seen the following warning message a couple of times on the first run of hypersearch.py, but not after:

> 2018-02-10 02:51:38.030610: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 516.70MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.

It's also taking REALLY long on my gtx 1070. Only 3 runs in about 12 hours, but I'll leave it running probably until Monday at least to see how it performs.

Also, I'm running with a custom data set (pulled from Bitfinex API, only has OHCLV data) with 133986 rows of data (Just about 3 months data). Is this enough, or should I pump more data into it?

**Comment by TalhaAsmal** [comment]
I noticed very strange GPU usage behaviour, shown below:

![image](https://user-images.githubusercontent.com/224751/36172884-ee11bf2c-110f-11e8-9f4b-4d93f1f47c6c.png)

My usage will be ~8%-10% for a long while, then suddenly spike and just as suddenly decrease. I've never seen this before in my NN training, and I wonder if that's why performance is so bad. Is there any way to profile or debug this behaviour? 

I'm running another hypersearch run tonight to see if the memory error persists.
